### ISSUE TITLE
[Suggestion] multi tor container service

### ISSUE THREAD

**Issue by ghost** [samirettali/tor-spider#1]
Hi,

Hope you are all well !

Here is an interesting multi tor container:
https://github.com/zet4/alpine-tor

It is a simple rotating tor pool with haproxy load balancer.

Hope that fits your needs.

Cheers,
X

**Comment by samirettali** [comment]
That's really similar to [https://github.com/trimstray/multitor](multitor), which looks more mantained to me.

**Comment by ghost** [comment]
Can you add the build context for the multitor service, https://github.com/samirettali/tor-spider/blob/master/docker-compose.yml#L32 ?

**Comment by ghost** [comment]
It uses the alpine/edge image, so it is already up to date, and do not need to be maintained that much. 
https://github.com/zet4/alpine-tor/blob/master/Dockerfile#L1

Also, it is lighter than multitor in terms of volume of files to maintain.

**Comment by samirettali** [comment]
> It uses the alpine/edge image, so it is already up to date, and do not need to be maintained that much.
> https://github.com/zet4/alpine-tor/blob/master/Dockerfile#L1
> 
> Also, it is lighter than multitor in terms of volume of files to maintain.

You're right, I'll switch to that as you can simply do a `docker pull` or pull it automatically with `docker-compose`.

9478d77c93d14194beea2f84b2d569e5d324c917

**Comment by samirettali** [comment]
> Can you add the build context for the multitor service, https://github.com/samirettali/tor-spider/blob/master/docker-compose.yml#L32 ?

I switched to another image in 9478d77c93d14194beea2f84b2d569e5d324c917 after the suggestion from @x0rzkov
