### ISSUE TITLE
[Improvement] filter the Input Collector from getting non-onion links

### ISSUE THREAD

**Issue by ghost** [samirettali/tor-spider#6]
Hi,

Hope you are all well !

I think we should filter link stored in MongoDB and to keep only '*.onion' links. 
At a large scale, it inserts too many classic http links.

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by samirettali** [comment]
Hi!
Sure, it sounds good, I just commited 04dd3340a4cc22f362e7b1b69212ddb4a54cc610, thanks!
